Feat/edit event
inlivedev/inlive-room pull request #141
Opened 2024-02-05 06:17 UTC by GagahGK

| My Event | <img width="582" alt="image" src="https://github.com/inlivedev/inlive-room/assets/20636513/7e72ce0c-92f8-480e-bda2-db2b262bb978"> | Event Detail | <img width="582" alt="image" src="https://github.com/inlivedev/inlive-room/assets/20636513/141fbe08-4502-469a-8423-b4f49d8a010d"> | Edit Event | <br><img width="582" alt="image" src="https://github.com/inlivedev/inlive-room/assets/20636513/618a5f4e-05dc-494d-8f6b-a57ff7d64f36"> |
| ---- | ---- | ---- | ---- | ---- | ---- |

This PR add the following features : 
* Ability to Edit Event
* Ability to Delete Event
* Update react-datepicker to fix crash on Firefox
* Added spinner to the button in create, edit, and delete operation
* Ability to navigate to event page using id
* Updated view in the Detail Event page : 
* Event Creator now can see the status of the event
* Changed Action Button, event creator now can edit, delete, and share their event quickly from the event page 

This PR also fixes the following important changes : 
* Updated FK references from `Event` table to Event_to_participant table, now when event is deleted it will perform cascade deletion the the Event_to_participant table
* a fix to the GetListEvent endpoint where the pagination didn't work properly
* fixed datetime related bug
* fix to the Update Event endpoint where it will remove the image when the it's updated without changing the image
* The event image on event detail page was hardcoded now uses value from `thumbnailUrl` from database
* move the server.ts from the `app` folder so during development the event image will be saved to `/volume/` not `/app/volume`

2024-02-06 04:50 UTC, faiq-naufal requested changes
Please check the comments. Thank you

2024-02-06 04:50 UTC, faiq-naufal commented on app/_features/event/components/event-detail.tsx
> +        </Button>
Similar to [this comment](https://github.com/inlivedev/inlive-room/pull/142#discussion_r1478094200). This edit button is just a navigation link right? Please use `<Link>` nextjs component with the `<Button>` instead.

2024-02-06 05:00 UTC, faiq-naufal commented
@GagahGK  Between edit event button vs copy link button. Which one is the primary CTA button? I think edit event button is the one that needs to be emphasized so the user can immediately guided when some data needed to be updated.
<img width="582" alt="302185264-141fbe08-4502-469a-8423-b4f49d8a010d" src="https://github.com/inlivedev/inlive-room/assets/43695578/2bce8add-aff9-42d9-bcfc-ad3886989134">

2024-02-06 06:30 UTC, faiq-naufal requested changes

2024-02-06 09:06 UTC, GagahGK commented
> @GagahGK Between edit event button vs copy link button. Which one is the primary CTA button? I think edit event button is the one that needs to be emphasized so the user can immediately guided when some data needed to be updated. <img alt="302185264-141fbe08-4502-469a-8423-b4f49d8a010d" width="250" src="https://private-user-images.githubusercontent.com/43695578/302505553-2bce8add-aff9-42d9-bcfc-ad3886989134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTAzMzcsIm5iZiI6MTcwNzIxMDAzNywicGF0aCI6Ii80MzY5NTU3OC8zMDI1MDU1NTMtMmJjZThhZGQtYWZmOS00MmQ5LWJjZmMtYWQzODg2OTg5MTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA5MDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZTE0ODgwZDU2MDVhOTc2Yzk1ZjgwY2IxNDc0YTMxMDdhMmRiYzNjM2VhODg4ZGQ5YWZhZTU5NzlmNjc2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x23RJpLo4yT83qKmyL72Yq720Vcr3rE9XvsOY7qpwqU">

I think Copy Link should be the primary CTA, since compared to Editing Event the Copy Link button will be used more frequently, User will perform editing to the event only if there's something needs to be revised which don't happen. but copying link to share the event will be done more frequently instead

2024-02-06 10:29 UTC, GagahGK commented
@faiq-naufal, i've revised to code as you requested : 

1. Card using Href : https://github.com/inlivedev/inlive-room/pull/141/commits/e580e2257daab4c36952f2fc0262a91fc277d346
2. `<Code>` tag now uses `<div>` instead : https://github.com/inlivedev/inlive-room/pull/141/commits/37340c6f77834d1046dd6d28f485125dfee7541c
3.  notFound() component issue : https://github.com/inlivedev/inlive-room/pull/141/commits/6d5798bddf94ddf7898a33b0e8724795e47b40d5
4.  about the default Local Storage Path : https://github.com/inlivedev/inlive-room/pull/141/commits/41d7588f6f2d18f4542adf055cbef8776e4a1452
5. oneliner code for getting cookie : https://github.com/inlivedev/inlive-room/pull/141/commits/d453c45df622bf5f7ca9da3f7cf9557aa85c21c3
6. remove useEffect for settign existing event : https://github.com/inlivedev/inlive-room/pull/141/commits/61f62c800639c83eeccdf3ff504b4e8e9f56188b https://github.com/inlivedev/inlive-room/pull/141/commits/8d3be5be6e517933e8ed04e16bc49fff23c0b7db

2024-02-06 10:57 UTC, faiq-naufal commented
I see the default local storage path has changed into `./storage`. There are some places where you haven't changed the code. I fixed it here [2e2d4d8](https://github.com/inlivedev/inlive-room/pull/141/commits/2e2d4d89902b0d55cb1016c4c8847acb1c01f0a1)

2024-02-06 11:00 UTC, faiq-naufal commented
> I think Copy Link should be the primary CTA, since compared to Editing Event the Copy Link button will be used more frequently, User will perform editing to the event only if there's something needs to be revised which don't happen. but copying link to share the event will be done more frequently instead

@GagahGK  I see, I think we also need insight from mas Ashar about this. But for now, I think it's fine to make the copy link primary cta.

2024-02-07 02:54 UTC, faiq-naufal approved these changes
LGTM

2024-02-07 02:55 UTC, merged